export const CATEGORY_NAME = {
	PERSONAL: 'PERSONAL',
	FAMILY: 'FAMILY',
	PRIVATE: 'PRIVATE',
	PUBLIC: 'PUBLIC',
}

export const CATEGORY_COLOR = {
	PERSONAL: '#009AC7',
	FAMILY: '#09B65A',
	PRIVATE: '#FF5252',
	PUBLIC: '#FDAE2E',
}
